name: CI/CD for Fullstack Todo Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies for the projekt
        run: |
          npm install

      - name: Run Automated Tests
        run: |
          npm test

      - name: Build image
        run: |
          docker build -t protasker-app .
